In [43]:
# --- Cell 2: Imports ---
from rdflib import Graph

# Notice we use 'src.filename' now!
from schema_definition import build_schema
from integrate_rQTLs import add_rqtl_to_graph
from integrate_gwas_catalog import enrich_graph_with_gwas
from integrate_open_targets import enrich_graph_with_opentargets
#from integrate_reactome import enrich_graph_with_reactome
from schema_definition import *
from execute_sparql import execute_sparql
from graphdb_engine import query_graphdb
from integrate_string import enrich_graph_with_string
from integrate_encode import enrich_graph_with_encode

# Integrate rQTLs

In [31]:
# 1. Initialize Graph
import random
from tqdm import tqdm
import glob
g = Graph()
g = build_schema(g)
number_of_rqtls= 100
rqtl_files = glob.glob("../data/json_files/*.json")
rqtl_files= random.sample(rqtl_files, number_of_rqtls)
# 2. Define Schema & Ontologies
rqtl_json_path = "../data/json_files/GCST90200330_GCST90200020.json"

# 3. Ingest Local JSON Data
print("\n[STEP 1] Ingesting local rQTL data...")
#add_rqtl_to_graph(rqtl_json_path, g)
for rqtl_file in tqdm(rqtl_files,total=number_of_rqtls):
    g = add_rqtl_to_graph(rqtl_file, g)

[STEP 1] Ingesting local rQTL data...

100%|██████████| 100/100 [00:05<00:00, 18.77it/s]

# Integrate GWAS Catalog

In [32]:
import numpy as np
# 4. Enrich with External APIs
number_of_snps= len(list(g.subjects(RDF.type, MTR.SNP)))

print("\n[STEP 2] Enriching with External Databases...")
g = enrich_graph_with_gwas(g,max_snps=number_of_snps)

[STEP 2] Enriching with External Databases...

--- Starting GWAS Catalog Integration (v2 API) ---
[1/79] Fetching v2 associations for rs662138...
   -> Found 10 significant associations!
[2/79] Fetching v2 associations for rs603424...
   -> Found 10 significant associations!
[3/79] Fetching v2 associations for rs174546...
   -> Found 10 significant associations!
[4/79] Fetching v2 associations for rs174564...
   -> Found 10 significant associations!
[5/79] Fetching v2 associations for rs174599...
   -> Found 10 significant associations!
[6/79] Fetching v2 associations for rs34400381...
   -> Found 10 significant associations!
[7/79] Fetching v2 associations for rs148982377...
   -> Found 10 significant associations!
[8/79] Fetching v2 associations for rs2472297...
   -> Found 10 significant associations!
[9/79] Fetching v2 associations for rs11211406...
   -> Found 2 significant associations!
[10/79] Fetching v2 associations for rs1165209...
   -> Found 6 significant associations!
[11/79] Fetching v2 associations for rs640777...
   -> Found 2 significant associations!
[12/79] Fetching v2 associations for rs1871194...
   -> Found 3 significant associations!
[13/79] Fetching v2 associations for rs2271060...
   -> No associated traits found in the GWAS Catalog for this SNP.
[14/79] Fetching v2 associations for rs174528...
   -> Found 10 significant associations!
[15/79] Fetching v2 associations for rs2804397...
   -> No associated traits found in the GWAS Catalog for this SNP.
[16/79] Fetching v2 associations for rs1047891...
   -> Found 10 significant associations!
[17/79] Fetching v2 associations for rs73355734...
   -> Found 2 significant associations!
[18/79] Fetching v2 associations for rs62129966...
   -> Found 10 significant associations!
[19/79] Fetching v2 associations for rs2062541...
   -> Found 10 significant associations!
[20/79] Fetching v2 associations for rs56398830...
   -> Found 10 significant associations!
[21/79] Fetching v2 associations for rs1495741...
   -> Found 10 significant associations!
[22/79] Fetching v2 associations for rs2130525...
   -> Found 1 significant associations!
[23/79] Fetching v2 associations for rs324420...
   -> Found 10 significant associations!
[24/79] Fetching v2 associations for rs4149026...
   -> No associated traits found in the GWAS Catalog for this SNP.
[25/79] Fetching v2 associations for rs4149056...
   -> Found 10 significant associations!
[26/79] Fetching v2 associations for rs102274...
   -> Found 10 significant associations!
[27/79] Fetching v2 associations for rs12356193...
   -> Found 6 significant associations!
[28/79] Fetching v2 associations for rs174568...
   -> Found 10 significant associations!
[29/79] Fetching v2 associations for rs61797339...
   -> Found 8 significant associations!
[30/79] Fetching v2 associations for rs9295741...
   -> Found 6 significant associations!
[31/79] Fetching v2 associations for rs12127402...
   -> No associated traits found in the GWAS Catalog for this SNP.
[32/79] Fetching v2 associations for rs28415528...
   -> Found 10 significant associations!
[33/79] Fetching v2 associations for rs676683...
   -> No associated traits found in the GWAS Catalog for this SNP.
[34/79] Fetching v2 associations for rs151154986...
   -> Found 10 significant associations!
[35/79] Fetching v2 associations for rs2657879...
   -> Found 10 significant associations!
[36/79] Fetching v2 associations for rs6546861...
   -> Found 10 significant associations!
[37/79] Fetching v2 associations for rs60782127...
   -> Found 10 significant associations!
[38/79] Fetching v2 associations for rs9738226...
   -> Found 10 significant associations!
[39/79] Fetching v2 associations for rs9925773...
   -> Found 9 significant associations!
[40/79] Fetching v2 associations for rs2393791...
   -> Found 10 significant associations!
[41/79] Fetching v2 associations for rs56078223...
   -> Found 2 significant associations!
[42/79] Fetching v2 associations for rs1767447...
   -> Found 1 significant associations!
[43/79] Fetching v2 associations for rs174584...
   -> Found 10 significant associations!
[44/79] Fetching v2 associations for rs4949674...
   -> No associated traits found in the GWAS Catalog for this SNP.
[45/79] Fetching v2 associations for rs17843966...
   -> Found 10 significant associations!
[46/79] Fetching v2 associations for rs12878001...
   -> Found 10 significant associations!
[47/79] Fetching v2 associations for rs7541058...
   -> Found 2 significant associations!
[48/79] Fetching v2 associations for rs72738356...
   -> Found 3 significant associations!
[49/79] Fetching v2 associations for rs2328895...
   -> Found 10 significant associations!
[50/79] Fetching v2 associations for rs1260326...
   -> Found 10 significant associations!
[51/79] Fetching v2 associations for rs112997117...
   -> Found 3 significant associations!
[52/79] Fetching v2 associations for rs35630725;rs1890452...
   -> No associated traits found in the GWAS Catalog for this SNP.
[53/79] Fetching v2 associations for rs924135...
   -> Found 10 significant associations!
[54/79] Fetching v2 associations for rs34048349...
   -> Found 1 significant associations!
[55/79] Fetching v2 associations for rs174565...
   -> Found 10 significant associations!
[56/79] Fetching v2 associations for rs102275...
   -> Found 10 significant associations!
[57/79] Fetching v2 associations for rs12074806...
   -> No associated traits found in the GWAS Catalog for this SNP.
[58/79] Fetching v2 associations for rs9379992...
   -> Found 2 significant associations!
[59/79] Fetching v2 associations for rs174560...
   -> Found 10 significant associations!
[60/79] Fetching v2 associations for rs174554...
   -> Found 10 significant associations!
[61/79] Fetching v2 associations for rs7573275...
   -> Found 2 significant associations!
[62/79] Fetching v2 associations for rs964184...
   -> Found 10 significant associations!
[63/79] Fetching v2 associations for rs270607...
   -> No associated traits found in the GWAS Catalog for this SNP.
[64/79] Fetching v2 associations for rs10426201...
   -> Found 7 significant associations!
[65/79] Fetching v2 associations for rs4507958...
   -> Found 10 significant associations!
[66/79] Fetching v2 associations for rs7157785...
   -> Found 10 significant associations!
[67/79] Fetching v2 associations for rs1321940...
   -> Found 10 significant associations!
[68/79] Fetching v2 associations for rs7533888...
   -> No associated traits found in the GWAS Catalog for this SNP.
[69/79] Fetching v2 associations for rs77420750...
   -> Found 7 significant associations!
[70/79] Fetching v2 associations for rs17101394...
   -> Found 10 significant associations!
[71/79] Fetching v2 associations for rs7523082...
   -> Found 1 significant associations!
[72/79] Fetching v2 associations for rs34760583;rs200076830...
   -> No associated traits found in the GWAS Catalog for this SNP.
[73/79] Fetching v2 associations for rs2185152...
   -> Found 7 significant associations!
[74/79] Fetching v2 associations for rs4804290...
   -> Found 1 significant associations!
[75/79] Fetching v2 associations for rs1177442...
   -> Found 10 significant associations!
[76/79] Fetching v2 associations for rs75406471...
   -> Found 10 significant associations!
[77/79] Fetching v2 associations for rs4881413...
   -> No associated traits found in the GWAS Catalog for this SNP.
[78/79] Fetching v2 associations for rs2151901...
   -> No associated traits found in the GWAS Catalog for this SNP.
[79/79] Fetching v2 associations for rs61741519...
   -> No associated traits found in the GWAS Catalog for this SNP.

--- GWAS Integration Complete ---

# Integrate Open Targets

In [33]:
number_of_genes=len(list(g.subjects(RDF.type, MTR.Gene)))

In [34]:

g = enrich_graph_with_opentargets(g, max_genes=number_of_genes)

--- Starting Open Targets Integration ---
Found 187 causal Genes in the local graph.
[1/187] Fetching OT data for SOD2...
   -> Found 4 safety liabilities!
   -> Found 10 top associated diseases!
[2/187] Fetching OT data for MRPL18...
   -> Found 10 top associated diseases!
[3/187] Fetching OT data for ABCC2...
   -> Found 20 safety liabilities!
   -> Found 10 top associated diseases!
[4/187] Fetching OT data for SCD...
   -> Found 4 safety liabilities!
   -> Found 10 top associated diseases!
[5/187] Fetching OT data for DNMBP...
   -> Found 10 top associated diseases!
[6/187] Fetching OT data for BLOC1S2...
   -> Found 10 top associated diseases!
[7/187] Fetching OT data for TMEM258...
   -> Found 10 top associated diseases!
[8/187] Fetching OT data for FADS1...
   -> Found 10 top associated diseases!
[9/187] Fetching OT data for FADS2...
   -> Found 10 top associated diseases!
[10/187] Fetching OT data for FADS3...
   -> Found 10 top associated diseases!
[11/187] Fetching OT data for FEN1...
   -> Found 10 top associated diseases!
[12/187] Fetching OT data for BEST1...
   -> Found 10 top associated diseases!
[13/187] Fetching OT data for PRDX5...
   -> Found 10 top associated diseases!
[14/187] Fetching OT data for DPF2...
   -> Found 10 top associated diseases!
[15/187] Fetching OT data for RIN1...
   -> Found 10 top associated diseases!
[16/187] Fetching OT data for POLA2...
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[17/187] Fetching OT data for C11orf68...
   -> Found 10 top associated diseases!
[18/187] Fetching OT data for LTBP3...
   -> Found 10 top associated diseases!
[19/187] Fetching OT data for ZKSCAN5...
   -> Found 10 top associated diseases!
[20/187] Fetching OT data for MEPCE...
   -> Found 10 top associated diseases!
[21/187] Fetching OT data for ZNF655...
   -> Found 10 top associated diseases!
[22/187] Fetching OT data for ARPC1A...
   -> Found 10 top associated diseases!
[23/187] Fetching OT data for LAMTOR4...
   -> Found 10 top associated diseases!
[24/187] Fetching OT data for AP4M1...
   -> Found 10 top associated diseases!
[25/187] Fetching OT data for ATP5J2...
   -> Found 10 top associated diseases!
[26/187] Fetching OT data for GATS...
   -> Found 10 top associated diseases!
[27/187] Fetching OT data for CNPY4...
   -> Found 10 top associated diseases!
[28/187] Fetching OT data for GAL3ST4...
   -> Found 10 top associated diseases!
[29/187] Fetching OT data for GS1-259H13.2...
   -> Found 7 top associated diseases!
[30/187] Fetching OT data for ZNF394...
   -> Found 10 top associated diseases!
[31/187] Fetching OT data for ARPC1B...
   -> Found 10 top associated diseases!
[32/187] Fetching OT data for TRIM4...
   -> Found 10 top associated diseases!
[33/187] Fetching OT data for CYP3A7...
   -> Found 1 safety liabilities!
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[34/187] Fetching OT data for PTCD1...
   -> Found 10 top associated diseases!
[35/187] Fetching OT data for BUD31...
   -> Found 10 top associated diseases!
[36/187] Fetching OT data for SMURF1...
   -> Found 10 top associated diseases!
[37/187] Fetching OT data for ZSCAN25...
   -> Found 10 top associated diseases!
[38/187] Fetching OT data for CYP3A5...
   -> Found 19 safety liabilities!
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[39/187] Fetching OT data for MAN2C1...
   -> Found 10 top associated diseases!
[40/187] Fetching OT data for STOML1...
   -> Found 10 top associated diseases!
[41/187] Fetching OT data for COMMD4...
   -> Found 10 top associated diseases!
[42/187] Fetching OT data for UBL7...
   -> Found 10 top associated diseases!
[43/187] Fetching OT data for ULK3...
   -> Found 10 top associated diseases!
[44/187] Fetching OT data for CYP4A11...
   -> Found 1 safety liabilities!
   -> Found 10 top associated diseases!
[45/187] Fetching OT data for CYP4A22...
   -> Found 1 safety liabilities!
   -> Found 10 top associated diseases!
[46/187] Fetching OT data for TAL1...
   -> Found 10 top associated diseases!
[47/187] Fetching OT data for CYP4Z1...
   -> Found 10 top associated diseases!
[48/187] Fetching OT data for CYP4X1...
   -> Found 10 top associated diseases!
[49/187] Fetching OT data for CYP4B1...
   -> Found 1 safety liabilities!
   -> Found 10 top associated diseases!
[50/187] Fetching OT data for PTPRCAP...
   -> Found 10 top associated diseases!
[51/187] Fetching OT data for CTSF...
   -> Found 10 top associated diseases!
[52/187] Fetching OT data for ACTN3...
   -> Found 10 top associated diseases!
[53/187] Fetching OT data for NUDT8...
   -> Found 10 top associated diseases!
[54/187] Fetching OT data for NDUFV1...
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[55/187] Fetching OT data for GSTP1...
   -> Found 11 safety liabilities!
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[56/187] Fetching OT data for CORO1B...
   -> Found 10 top associated diseases!
[57/187] Fetching OT data for PITPNM1...
   -> Found 10 top associated diseases!
[58/187] Fetching OT data for RPS6KB2...
   -> Found 6 known drugs!
   -> Found 10 top associated diseases!
[59/187] Fetching OT data for AIP...
   -> Found 10 top associated diseases!
[60/187] Fetching OT data for CERS4...
   -> Found 10 top associated diseases!
[61/187] Fetching OT data for ACSM3...
   -> Found 10 top associated diseases!
[62/187] Fetching OT data for ACSM5...
   -> Found 10 top associated diseases!
[63/187] Fetching OT data for PDILT...
   -> Found 10 top associated diseases!
[64/187] Fetching OT data for ACSM1...
   -> Found 10 top associated diseases!
[65/187] Fetching OT data for AC004381.6...
   -> AC004381.6 not found in Open Targets database.
[66/187] Fetching OT data for THUMPD1...
   -> Found 10 top associated diseases!
[67/187] Fetching OT data for PKD2L1...
   -> Found 10 top associated diseases!
[68/187] Fetching OT data for RP11-649A18.12...
   -> RP11-649A18.12 not found in Open Targets database.
[69/187] Fetching OT data for ACOX1...
   -> Found 1 safety liabilities!
   -> Found 10 top associated diseases!
[70/187] Fetching OT data for WBP2...
   -> Found 10 top associated diseases!
[71/187] Fetching OT data for PRPSAP1...
   -> Found 10 top associated diseases!
[72/187] Fetching OT data for CDK3...
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[73/187] Fetching OT data for MRPL38...
   -> Found 10 top associated diseases!
[74/187] Fetching OT data for NUCB1...
   -> Found 10 top associated diseases!
[75/187] Fetching OT data for SULT2A1...
   -> Found 1 safety liabilities!
   -> Found 10 top associated diseases!
[76/187] Fetching OT data for GLTSCR2...
   -> Found 10 top associated diseases!
[77/187] Fetching OT data for ABCC1...
   -> Found 5 safety liabilities!
   -> Found 1 known drugs!
   -> Found 10 top associated diseases!
[78/187] Fetching OT data for NAT2...
   -> Found 12 safety liabilities!
   -> Found 10 top associated diseases!
[79/187] Fetching OT data for THEM4...
   -> Found 10 top associated diseases!
[80/187] Fetching OT data for S100A10...
   -> Found 10 top associated diseases!
[81/187] Fetching OT data for RIIAD1...
   -> Found 10 top associated diseases!
[82/187] Fetching OT data for FAAH...
   -> Found 8 safety liabilities!
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[83/187] Fetching OT data for RAD54L...
   -> Found 10 top associated diseases!
[84/187] Fetching OT data for NSUN4...
   -> Found 10 top associated diseases!
[85/187] Fetching OT data for CCDC17...
   -> Found 10 top associated diseases!
[86/187] Fetching OT data for PRDX1...
   -> Found 10 top associated diseases!
[87/187] Fetching OT data for IPP...
   -> Found 10 top associated diseases!
[88/187] Fetching OT data for POMGNT1...
   -> Found 10 top associated diseases!
[89/187] Fetching OT data for TESK2...
   -> Found 10 top associated diseases!
[90/187] Fetching OT data for PIK3R3...
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[91/187] Fetching OT data for C12orf39...
   -> Found 10 top associated diseases!
[92/187] Fetching OT data for SLC22A6...
   -> Found 2 safety liabilities!
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[93/187] Fetching OT data for SLC16A9...
   -> Found 10 top associated diseases!
[94/187] Fetching OT data for ACADM...
   -> Found 10 top associated diseases!
[95/187] Fetching OT data for CRYZ...
   -> Found 10 top associated diseases!
[96/187] Fetching OT data for MSH4...
   -> Found 10 top associated diseases!
[97/187] Fetching OT data for RABGGTB...
   -> Found 10 top associated diseases!
[98/187] Fetching OT data for SYCP2L...
   -> Found 10 top associated diseases!
[99/187] Fetching OT data for ELOVL2...
   -> Found 10 top associated diseases!
[100/187] Fetching OT data for CTSK...
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[101/187] Fetching OT data for C2CD4D...
   -> Found 10 top associated diseases!
[102/187] Fetching OT data for C6orf201...
   -> Found 1 top associated diseases!
[103/187] Fetching OT data for ECI2...
   -> Found 10 top associated diseases!
[104/187] Fetching OT data for FAM217A...
   -> Found 10 top associated diseases!
[105/187] Fetching OT data for ACOT2...
   -> Found 10 top associated diseases!
[106/187] Fetching OT data for DNAL1...
   -> Found 10 top associated diseases!
[107/187] Fetching OT data for DCAF4...
   -> Found 10 top associated diseases!
[108/187] Fetching OT data for ACOT1...
   -> Found 10 top associated diseases!
[109/187] Fetching OT data for ISCA2...
   -> Found 10 top associated diseases!
[110/187] Fetching OT data for PSEN1...
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[111/187] Fetching OT data for NUMB...
   -> Found 10 top associated diseases!
[112/187] Fetching OT data for ACOT4...
   -> Found 10 top associated diseases!
[113/187] Fetching OT data for SPRYD4...
   -> Found 10 top associated diseases!
[114/187] Fetching OT data for RBMS2...
   -> Found 10 top associated diseases!
[115/187] Fetching OT data for ALMS1-IT1...
   -> Found 3 top associated diseases!
[116/187] Fetching OT data for DGUOK...
   -> Found 10 top associated diseases!
[117/187] Fetching OT data for ALMS1...
   -> Found 10 top associated diseases!
[118/187] Fetching OT data for NAT8...
   -> Found 10 top associated diseases!
[119/187] Fetching OT data for GCN1L1...
   -> Found 10 top associated diseases!
[120/187] Fetching OT data for C12orf43...
   -> Found 10 top associated diseases!
[121/187] Fetching OT data for DUS2L...
   -> Found 10 top associated diseases!
[122/187] Fetching OT data for FHOD1...
   -> Found 10 top associated diseases!
[123/187] Fetching OT data for SLC7A6...
   -> Found 10 top associated diseases!
[124/187] Fetching OT data for ACD...
   -> Found 10 top associated diseases!
[125/187] Fetching OT data for E2F4...
   -> Found 1 known drugs!
   -> Found 10 top associated diseases!
[126/187] Fetching OT data for TRADD...
   -> Found 10 top associated diseases!
[127/187] Fetching OT data for FAM65A...
   -> Found 10 top associated diseases!
[128/187] Fetching OT data for PLA2G15...
   -> Found 10 top associated diseases!
[129/187] Fetching OT data for NFATC3...
   -> Found 10 top associated diseases!
[130/187] Fetching OT data for PRMT7...
   -> Found 10 top associated diseases!
[131/187] Fetching OT data for SMPD3...
   -> Found 10 top associated diseases!
[132/187] Fetching OT data for SLC7A6OS...
   -> Found 10 top associated diseases!
[133/187] Fetching OT data for DUS2...
   -> Found 10 top associated diseases!
[134/187] Fetching OT data for NBPF3...
   -> Found 10 top associated diseases!
[135/187] Fetching OT data for NBPF2P...
[136/187] Fetching OT data for ALPL...
   -> Found 10 top associated diseases!
[137/187] Fetching OT data for LURAP1...
   -> Found 10 top associated diseases!
[138/187] Fetching OT data for ETFDH...
   -> Found 10 top associated diseases!
[139/187] Fetching OT data for PPID...
   -> Found 10 top associated diseases!
[140/187] Fetching OT data for RP3-414A15.2...
   -> RP3-414A15.2 not found in Open Targets database.
[141/187] Fetching OT data for PTGR2...
   -> Found 10 top associated diseases!
[142/187] Fetching OT data for HEATR4...
   -> Found 10 top associated diseases!
[143/187] Fetching OT data for ZFYVE1...
   -> Found 10 top associated diseases!
[144/187] Fetching OT data for ZNF512...
   -> Found 10 top associated diseases!
[145/187] Fetching OT data for AC093690.1...
   -> AC093690.1 not found in Open Targets database.
[146/187] Fetching OT data for AC109828.1...
   -> AC109828.1 not found in Open Targets database.
[147/187] Fetching OT data for GTF3C2...
   -> Found 10 top associated diseases!
[148/187] Fetching OT data for NRBP1...
   -> Found 10 top associated diseases!
[149/187] Fetching OT data for GPN1...
   -> Found 10 top associated diseases!
[150/187] Fetching OT data for TRIM54...
   -> Found 10 top associated diseases!
[151/187] Fetching OT data for PPM1G...
   -> Found 10 top associated diseases!
[152/187] Fetching OT data for CHUK...
   -> Found 1 safety liabilities!
   -> Found 10 top associated diseases!
[153/187] Fetching OT data for CTSS...
   -> Found 2 known drugs!
   -> Found 10 top associated diseases!
[154/187] Fetching OT data for MOSPD3...
   -> Found 10 top associated diseases!
[155/187] Fetching OT data for AC004893.11...
   -> AC004893.11 not found in Open Targets database.
[156/187] Fetching OT data for TECPR1...
   -> Found 10 top associated diseases!
[157/187] Fetching OT data for CPSF4...
   -> Found 10 top associated diseases!
[158/187] Fetching OT data for GJC3...
   -> Found 10 top associated diseases!
[159/187] Fetching OT data for MYRF...
   -> Found 10 top associated diseases!
[160/187] Fetching OT data for NPL...
   -> Found 10 top associated diseases!
[161/187] Fetching OT data for LAMC1...
   -> Found 10 known drugs!
   -> Found 10 top associated diseases!
[162/187] Fetching OT data for DHX9...
   -> Found 10 top associated diseases!
[163/187] Fetching OT data for ALMS1P...
   -> Found 8 top associated diseases!
[164/187] Fetching OT data for AC092653.5...
   -> AC092653.5 not found in Open Targets database.
[165/187] Fetching OT data for TPRKB...
   -> Found 10 top associated diseases!
[166/187] Fetching OT data for DCTN1...
   -> Found 10 top associated diseases!
[167/187] Fetching OT data for STAMBP...
   -> Found 10 top associated diseases!
[168/187] Fetching OT data for RAB11FIP5...
   -> Found 10 top associated diseases!
[169/187] Fetching OT data for DUSP11...
   -> Found 10 top associated diseases!
[170/187] Fetching OT data for FBXO41...
   -> Found 10 top associated diseases!
[171/187] Fetching OT data for ZNF259...
   -> Found 10 top associated diseases!
[172/187] Fetching OT data for SLC22A4...
   -> Found 10 top associated diseases!
[173/187] Fetching OT data for AC034220.3...
   -> AC034220.3 not found in Open Targets database.
[174/187] Fetching OT data for SLC22A5...
   -> Found 1 safety liabilities!
   -> Found 10 top associated diseases!
[175/187] Fetching OT data for P4HA2...
   -> Found 10 top associated diseases!
[176/187] Fetching OT data for PDLIM4...
   -> Found 10 top associated diseases!
[177/187] Fetching OT data for KIF3A...
   -> Found 10 top associated diseases!
[178/187] Fetching OT data for ACSL6...
   -> Found 10 top associated diseases!
[179/187] Fetching OT data for CDC42SE2...
   -> Found 10 top associated diseases!
[180/187] Fetching OT data for SPTLC3...
   -> Found 10 top associated diseases!
[181/187] Fetching OT data for ISM1...
   -> Found 10 top associated diseases!
[182/187] Fetching OT data for SLC44A5...
   -> Found 10 top associated diseases!
[183/187] Fetching OT data for AC004791.2...
   -> AC004791.2 not found in Open Targets database.
[184/187] Fetching OT data for CYP4F11...
   -> Found 10 top associated diseases!
[185/187] Fetching OT data for IFT172...
   -> Found 10 top associated diseases!
[186/187] Fetching OT data for RAB3IL1...
   -> Found 10 top associated diseases!
[187/187] Fetching OT data for TEX38...
   -> Found 10 top associated diseases!

--- Open Targets Integration Complete ---

# Integrate STRING database

In [35]:
g=enrich_graph_with_string(g)

--- Starting STRING Database Integration ---
Found 187 genes. Fetching interaction network...
Successfully retrieved 200 interactions from STRING.
--- STRING Integration Complete ---

# Integrate ENCODE database

In [46]:
g=enrich_graph_with_encode(g)

2026-03-07 14:43:38,217 [INFO] --- Starting ENCODE Epigenetic Integration (via Ensembl) ---
2026-03-07 14:43:38,218 [INFO] [1/79] Checking ENCODE regulatory overlaps for rs662138...
2026-03-07 14:43:38,922 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:39,023 [INFO] [2/79] Checking ENCODE regulatory overlaps for rs603424...
2026-03-07 14:43:39,747 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:39,848 [INFO] [3/79] Checking ENCODE regulatory overlaps for rs174546...
2026-03-07 14:43:40,721 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:40,822 [INFO] [4/79] Checking ENCODE regulatory overlaps for rs174564...
2026-03-07 14:43:41,607 [INFO]    -> Found 1 ENCODE regulatory features!
2026-03-07 14:43:41,758 [INFO] [5/79] Checking ENCODE regulatory overlaps for rs174599...
2026-03-07 14:43:42,574 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:42,675 [INFO] [6/79] Checking ENCODE regulatory overlaps for rs34400381...
2026-03-07 14:43:43,377 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:43,479 [INFO] [7/79] Checking ENCODE regulatory overlaps for rs148982377...
2026-03-07 14:43:46,514 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:46,615 [INFO] [8/79] Checking ENCODE regulatory overlaps for rs2472297...
2026-03-07 14:43:47,649 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:47,813 [INFO] [9/79] Checking ENCODE regulatory overlaps for rs11211406...
2026-03-07 14:43:48,649 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:48,750 [INFO] [10/79] Checking ENCODE regulatory overlaps for rs1165209...
2026-03-07 14:43:49,479 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:49,581 [INFO] [11/79] Checking ENCODE regulatory overlaps for rs640777...
2026-03-07 14:43:50,313 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:50,414 [INFO] [12/79] Checking ENCODE regulatory overlaps for rs1871194...
2026-03-07 14:43:51,186 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:51,288 [INFO] [13/79] Checking ENCODE regulatory overlaps for rs2271060...
2026-03-07 14:43:52,016 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:52,117 [INFO] [14/79] Checking ENCODE regulatory overlaps for rs174528...
2026-03-07 14:43:53,733 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:53,834 [INFO] [15/79] Checking ENCODE regulatory overlaps for rs2804397...
2026-03-07 14:43:54,586 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:54,688 [INFO] [16/79] Checking ENCODE regulatory overlaps for rs1047891...
2026-03-07 14:43:56,929 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:43:57,031 [INFO] [17/79] Checking ENCODE regulatory overlaps for rs73355734...
2026-03-07 14:43:57,898 [INFO]    -> Found 1 ENCODE regulatory features!
2026-03-07 14:43:58,051 [INFO] [18/79] Checking ENCODE regulatory overlaps for rs62129966...
2026-03-07 14:44:00,053 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:00,155 [INFO] [19/79] Checking ENCODE regulatory overlaps for rs2062541...
2026-03-07 14:44:01,440 [INFO]    -> Found 1 ENCODE regulatory features!
2026-03-07 14:44:01,598 [INFO] [20/79] Checking ENCODE regulatory overlaps for rs56398830...
2026-03-07 14:44:03,045 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:03,147 [INFO] [21/79] Checking ENCODE regulatory overlaps for rs1495741...
2026-03-07 14:44:04,005 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:04,107 [INFO] [22/79] Checking ENCODE regulatory overlaps for rs2130525...
2026-03-07 14:44:04,916 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:05,018 [INFO] [23/79] Checking ENCODE regulatory overlaps for rs324420...
2026-03-07 14:44:06,743 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:06,845 [INFO] [24/79] Checking ENCODE regulatory overlaps for rs4149026...
2026-03-07 14:44:08,601 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:08,702 [INFO] [25/79] Checking ENCODE regulatory overlaps for rs4149056...
2026-03-07 14:44:10,223 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:10,324 [INFO] [26/79] Checking ENCODE regulatory overlaps for rs102274...
2026-03-07 14:44:11,795 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:11,896 [INFO] [27/79] Checking ENCODE regulatory overlaps for rs12356193...
2026-03-07 14:44:12,830 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:12,932 [INFO] [28/79] Checking ENCODE regulatory overlaps for rs174568...
2026-03-07 14:44:14,698 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:14,800 [INFO] [29/79] Checking ENCODE regulatory overlaps for rs61797339...
2026-03-07 14:44:18,548 [INFO]    -> Found 1 ENCODE regulatory features!
2026-03-07 14:44:18,706 [INFO] [30/79] Checking ENCODE regulatory overlaps for rs9295741...
2026-03-07 14:44:19,630 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:19,731 [INFO] [31/79] Checking ENCODE regulatory overlaps for rs12127402...
2026-03-07 14:44:20,490 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:20,592 [INFO] [32/79] Checking ENCODE regulatory overlaps for rs28415528...
2026-03-07 14:44:21,304 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:21,406 [INFO] [33/79] Checking ENCODE regulatory overlaps for rs676683...
2026-03-07 14:44:22,119 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:22,221 [INFO] [34/79] Checking ENCODE regulatory overlaps for rs151154986...
2026-03-07 14:44:23,547 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:23,649 [INFO] [35/79] Checking ENCODE regulatory overlaps for rs2657879...
2026-03-07 14:44:25,321 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:25,423 [INFO] [36/79] Checking ENCODE regulatory overlaps for rs6546861...
2026-03-07 14:44:26,126 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:26,228 [INFO] [37/79] Checking ENCODE regulatory overlaps for rs60782127...
2026-03-07 14:44:27,714 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:27,816 [INFO] [38/79] Checking ENCODE regulatory overlaps for rs9738226...
2026-03-07 14:44:28,651 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:28,752 [INFO] [39/79] Checking ENCODE regulatory overlaps for rs9925773...
2026-03-07 14:44:29,491 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:29,593 [INFO] [40/79] Checking ENCODE regulatory overlaps for rs2393791...
2026-03-07 14:44:30,330 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:30,431 [INFO] [41/79] Checking ENCODE regulatory overlaps for rs56078223...
2026-03-07 14:44:31,143 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:31,244 [INFO] [42/79] Checking ENCODE regulatory overlaps for rs1767447...
2026-03-07 14:44:32,661 [INFO]    -> Found 1 ENCODE regulatory features!
2026-03-07 14:44:32,818 [INFO] [43/79] Checking ENCODE regulatory overlaps for rs174584...
2026-03-07 14:44:33,529 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:33,630 [INFO] [44/79] Checking ENCODE regulatory overlaps for rs4949674...
2026-03-07 14:44:34,354 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:34,455 [INFO] [45/79] Checking ENCODE regulatory overlaps for rs17843966...
2026-03-07 14:44:35,179 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:35,280 [INFO] [46/79] Checking ENCODE regulatory overlaps for rs12878001...
2026-03-07 14:44:36,033 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:36,134 [INFO] [47/79] Checking ENCODE regulatory overlaps for rs7541058...
2026-03-07 14:44:36,847 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:36,948 [INFO] [48/79] Checking ENCODE regulatory overlaps for rs72738356...
2026-03-07 14:44:37,682 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:37,783 [INFO] [49/79] Checking ENCODE regulatory overlaps for rs2328895...
2026-03-07 14:44:38,513 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:38,615 [INFO] [50/79] Checking ENCODE regulatory overlaps for rs1260326...
2026-03-07 14:44:39,729 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:39,830 [INFO] [51/79] Checking ENCODE regulatory overlaps for rs112997117...
2026-03-07 14:44:40,639 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:40,741 [INFO] [52/79] Checking ENCODE regulatory overlaps for rs35630725;rs1890452...
2026-03-07 14:44:41,084 [INFO]    -> Could not find genomic coordinates for rs35630725;rs1890452.
2026-03-07 14:44:41,185 [INFO] [53/79] Checking ENCODE regulatory overlaps for rs924135...
2026-03-07 14:44:42,688 [INFO]    -> Found 1 ENCODE regulatory features!
2026-03-07 14:44:42,843 [INFO] [54/79] Checking ENCODE regulatory overlaps for rs34048349...
2026-03-07 14:44:43,566 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:43,667 [INFO] [55/79] Checking ENCODE regulatory overlaps for rs174565...
2026-03-07 14:44:45,244 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:45,345 [INFO] [56/79] Checking ENCODE regulatory overlaps for rs102275...
2026-03-07 14:44:46,056 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:46,158 [INFO] [57/79] Checking ENCODE regulatory overlaps for rs12074806...
2026-03-07 14:44:46,857 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:46,958 [INFO] [58/79] Checking ENCODE regulatory overlaps for rs9379992...
2026-03-07 14:44:47,689 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:47,789 [INFO] [59/79] Checking ENCODE regulatory overlaps for rs174560...
2026-03-07 14:44:48,647 [INFO]    -> Found 1 ENCODE regulatory features!
2026-03-07 14:44:48,807 [INFO] [60/79] Checking ENCODE regulatory overlaps for rs174554...
2026-03-07 14:44:49,508 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:49,609 [INFO] [61/79] Checking ENCODE regulatory overlaps for rs7573275...
2026-03-07 14:44:50,373 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:50,475 [INFO] [62/79] Checking ENCODE regulatory overlaps for rs964184...
2026-03-07 14:44:51,230 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:51,331 [INFO] [63/79] Checking ENCODE regulatory overlaps for rs270607...
2026-03-07 14:44:52,869 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:52,969 [INFO] [64/79] Checking ENCODE regulatory overlaps for rs10426201...
2026-03-07 14:44:53,684 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:53,785 [INFO] [65/79] Checking ENCODE regulatory overlaps for rs4507958...
2026-03-07 14:44:54,505 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:54,606 [INFO] [66/79] Checking ENCODE regulatory overlaps for rs7157785...
2026-03-07 14:44:55,337 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:55,438 [INFO] [67/79] Checking ENCODE regulatory overlaps for rs1321940...
2026-03-07 14:44:56,347 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:56,449 [INFO] [68/79] Checking ENCODE regulatory overlaps for rs7533888...
2026-03-07 14:44:57,186 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:57,288 [INFO] [69/79] Checking ENCODE regulatory overlaps for rs77420750...
2026-03-07 14:44:58,197 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:58,298 [INFO] [70/79] Checking ENCODE regulatory overlaps for rs17101394...
2026-03-07 14:44:59,017 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:59,118 [INFO] [71/79] Checking ENCODE regulatory overlaps for rs7523082...
2026-03-07 14:44:59,824 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:44:59,925 [INFO] [72/79] Checking ENCODE regulatory overlaps for rs34760583;rs200076830...
2026-03-07 14:45:00,253 [INFO]    -> Could not find genomic coordinates for rs34760583;rs200076830.
2026-03-07 14:45:00,360 [INFO] [73/79] Checking ENCODE regulatory overlaps for rs2185152...
2026-03-07 14:45:01,068 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:45:01,169 [INFO] [74/79] Checking ENCODE regulatory overlaps for rs4804290...
2026-03-07 14:45:01,906 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:45:02,007 [INFO] [75/79] Checking ENCODE regulatory overlaps for rs1177442...
2026-03-07 14:45:02,759 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:45:02,861 [INFO] [76/79] Checking ENCODE regulatory overlaps for rs75406471...
2026-03-07 14:45:03,617 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:45:03,718 [INFO] [77/79] Checking ENCODE regulatory overlaps for rs4881413...
2026-03-07 14:45:04,452 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:45:04,554 [INFO] [78/79] Checking ENCODE regulatory overlaps for rs2151901...
2026-03-07 14:45:05,596 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:45:05,697 [INFO] [79/79] Checking ENCODE regulatory overlaps for rs61741519...
2026-03-07 14:45:06,435 [INFO]    -> No overlapping epigenetic features found.
2026-03-07 14:45:06,536 [INFO] --- ENCODE Integration Complete ---

In [52]:
import pandas as pd
df_report=pd.read_csv("../output/encode_mapping_report.csv")

In [55]:
df_report[df_report.Status=="Mapped"]

           SNP  Status  Features_Found
3     rs174564  Mapped               1
16  rs73355734  Mapped               1
18   rs2062541  Mapped               1
28  rs61797339  Mapped               1
41   rs1767447  Mapped               1
52    rs924135  Mapped               1
58    rs174560  Mapped               1

In [ ]:
# Integrate STRING database

In [39]:
from graphdb_engine import query_graphdb

# The optimized query from earlier
optimized_gwas_query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX biolink: <https://w3id.org/biolink/vocab/>
PREFIX oban: <http://purl.org/oban/>
PREFIX mtr: <https://metabolite-ratio-app.unil.ch/rqtl/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?snp ?ratio_name ?trait_name ?gwas_p_value ?gwas_beta
WHERE {
  # 1. Get the rQTL Associations
  ?ratio a mtr:MetaboliteRatio ;
         rdfs:label ?ratio_name .

  ?rqtl_assoc a oban:association ;
              oban:has_object ?ratio ;
              oban:has_subject ?snp .

  # 2. Get the GWAS Associations for those exact SNPs
  ?gwas_assoc a biolink:Association ;
              biolink:has_subject ?snp ;
              biolink:has_object ?trait ;
              mtr:p_value ?gwas_p_value .

  ?trait rdfs:label ?trait_name .

  # 3. Grab the beta if it exists
  OPTIONAL { ?gwas_assoc mtr:beta ?gwas_beta . }

  # 4. Filter for genome-wide significance
  FILTER (?gwas_p_value < 0.00000005)
}
ORDER BY ?gwas_p_value
LIMIT 10

"""

# Execute the query against GraphDB!
# Note: Ensure the 'repo_name' matches what you named it in the GraphDB Workbench
df_results = query_graphdb(optimized_gwas_query, repo_name="mtrKG")

# Display the results
display(df_results)

Sending query to GraphDB (mtrKG)...
Success! Retrieved 10 rows.

,snp,ratio_name,trait_name,gwas_p_value,gwas_beta
0,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,2e-286,-0.35285
1,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,2e-286,-0.352894
2,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,2e-286,-0.352233
3,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,2e-286,-0.351561
4,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,2e-286,-0.350063
5,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,2e-286,-0.348978
6,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,2e-286,-0.245665
7,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,5.0000000000000003e-284,-0.35285
8,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,5.0000000000000003e-284,-0.352894
9,http://identifiers.org/dbsnp/rs102275,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero...",lysophosphatidylethanolamine measurement,5.0000000000000003e-284,-0.352233

In [15]:
query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX biolink: <https://w3id.org/biolink/vocab/>
PREFIX oban: <http://purl.org/oban/>
PREFIX mtr: <https://metabolite-ratio-app.unil.ch/rqtl/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?snp ?ratio_name ?trait_name ?gwas_p_value ?gwas_beta
WHERE {
  ?rqtl_assoc a oban:association ;
              oban:has_subject ?snp ;
              oban:has_object ?ratio .
  ?ratio rdfs:label ?ratio_name .

  ?gwas_assoc a biolink:Association ;
              biolink:has_subject ?snp ;
              biolink:has_object ?trait ;
              mtr:p_value ?gwas_p_value .
  ?trait rdfs:label ?trait_name .

  OPTIONAL { ?gwas_assoc mtr:beta ?gwas_beta . }

  FILTER (?gwas_p_value < 0.00000005)
}
ORDER BY ?gwas_p_value
LIMIT 10
"""

In [16]:
print(g.serialize(format="turtle"))

@prefix biolink: <https://w3id.org/biolink/vocab/> .
@prefix chebi: <http://purl.obolibrary.org/obo/CHEBI_> .
@prefix dbsnp: <http://identifiers.org/dbsnp/> .
@prefix efo: <http://www.ebi.ac.uk/efo/> .
@prefix hmdb: <http://identifiers.org/hmdb/> .
@prefix mtr: <https://metabolite-ratio-app.unil.ch/rqtl/> .
@prefix ns1: <http://purl.org/oban/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix pubmed: <https://pubmed.ncbi.nlm.nih.gov/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sio: <http://semanticscience.org/resource/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ns1:has_object owl:equivalentProperty biolink:has_object .

ns1:has_subject owl:equivalentProperty biolink:has_subject .

<https://metabolite-ratio-app.unil.ch/ontology> a owl:Ontology ;
    rdfs:label "rQTL Metabolic Ratio Ontology" ;
    rdfs:comment "A schema defining genetically regulated metabolic reactions." .

mtr:Assoc_rs118072533_GCST90200267_GCST90200523 a ns1:association ;
    ns1:has_object mtr:GCST90200267_GCST90200523 ;
    ns1:has_subject dbsnp:rs118072533 ;
    mtr:beta "-0.3099658999999999"^^xsd:float ;
    mtr:denominator_driven true ;
    mtr:effect_allele "T" ;
    mtr:maf "0.0594436"^^xsd:float ;
    mtr:numerator_driven false ;
    mtr:pgain "258481406.4066837"^^xsd:float ;
    mtr:reference_allele "G" ;
    mtr:se "0.0309353634862265"^^xsd:float ;
    mtr:z_score "-10.019791755089846"^^xsd:float .

mtr:Assoc_rs12095130_GCST90200529_GCST90200530 a ns1:association ;
    ns1:has_object mtr:GCST90200529_GCST90200530 ;
    ns1:has_subject dbsnp:rs12095130 ;
    mtr:beta "-0.1953801"^^xsd:float ;
    mtr:denominator_driven false ;
    mtr:effect_allele "A" ;
    mtr:maf "0.12405"^^xsd:float ;
    mtr:numerator_driven false ;
    mtr:pgain "144612609.2332758"^^xsd:float ;
    mtr:reference_allele "T" ;
    mtr:se "0.0244228853743358"^^xsd:float ;
    mtr:z_score "-7.999877860676936"^^xsd:float .

mtr:Assoc_rs13138057_GCST90200267_GCST90200523 a ns1:association ;
    ns1:has_object mtr:GCST90200267_GCST90200523 ;
    ns1:has_subject dbsnp:rs13138057 ;
    mtr:beta "0.1678463"^^xsd:float ;
    mtr:denominator_driven true ;
    mtr:effect_allele "C" ;
    mtr:maf "0.208539"^^xsd:float ;
    mtr:numerator_driven false ;
    mtr:pgain "1958007201.472384"^^xsd:float ;
    mtr:reference_allele "T" ;
    mtr:se "0.0181338004896465"^^xsd:float ;
    mtr:z_score "9.255991323817147"^^xsd:float .

mtr:Assoc_rs174560_GCST90199710_GCST90200086 a ns1:association ;
    ns1:has_object mtr:GCST90199710_GCST90200086 ;
    ns1:has_subject dbsnp:rs174560 ;
    mtr:beta "0.429613"^^xsd:float ;
    mtr:denominator_driven true ;
    mtr:effect_allele "C" ;
    mtr:maf "0.341651"^^xsd:float ;
    mtr:numerator_driven true ;
    mtr:pgain "2.850566943533151e+24"^^xsd:float ;
    mtr:reference_allele "T" ;
    mtr:se "0.0258768563042984"^^xsd:float ;
    mtr:z_score "16.602209903242244"^^xsd:float .

mtr:Assoc_rs174564_GCST90200330_GCST90199899 a ns1:association ;
    ns1:has_object mtr:GCST90200330_GCST90199899 ;
    ns1:has_subject dbsnp:rs174564 ;
    mtr:beta "0.441299"^^xsd:float ;
    mtr:denominator_driven true ;
    mtr:effect_allele "G" ;
    mtr:maf "0.344903"^^xsd:float ;
    mtr:numerator_driven true ;
    mtr:pgain "3.5031345380532565e+26"^^xsd:float ;
    mtr:reference_allele "A" ;
    mtr:se "0.0213008545024095"^^xsd:float ;
    mtr:z_score "20.71743177955987"^^xsd:float .

mtr:Assoc_rs1902023_GCST90200267_GCST90200523 a ns1:association ;
    ns1:has_object mtr:GCST90200267_GCST90200523 ;
    ns1:has_subject dbsnp:rs1902023 ;
    mtr:beta "0.2432559999999999"^^xsd:float ;
    mtr:denominator_driven true ;
    mtr:effect_allele "C" ;
    mtr:maf "0.477031"^^xsd:float ;
    mtr:numerator_driven true ;
    mtr:pgain "5.744826075989714e+42"^^xsd:float ;
    mtr:reference_allele "A" ;
    mtr:se "0.0145575833152277"^^xsd:float ;
    mtr:z_score "16.709916387395577"^^xsd:float .

mtr:Assoc_rs2151901_GCST90199851_GCST90199752 a ns1:association ;
    ns1:has_object mtr:GCST90199851_GCST90199752 ;
    ns1:has_subject dbsnp:rs2151901 ;
    mtr:beta "-0.2138827999999999"^^xsd:float ;
    mtr:denominator_driven false ;
    mtr:effect_allele "C" ;
    mtr:maf "0.14973"^^xsd:float ;
    mtr:numerator_driven true ;
    mtr:pgain "32355453697066.49"^^xsd:float ;
    mtr:reference_allele "A" ;
    mtr:se "0.0209994882412783"^^xsd:float ;
    mtr:z_score "-10.185143444570883"^^xsd:float .

mtr:Assoc_rs272849_GCST90199713_GCST90199730 a ns1:association ;
    ns1:has_object mtr:GCST90199713_GCST90199730 ;
    ns1:has_subject dbsnp:rs272849 ;
    mtr:beta "-0.1649893"^^xsd:float ;
    mtr:denominator_driven true ;
    mtr:effect_allele "A" ;
    mtr:maf "0.3733689999999999"^^xsd:float ;
    mtr:numerator_driven false ;
    mtr:pgain "22545274226434.195"^^xsd:float ;
    mtr:reference_allele "G" ;
    mtr:se "0.0157889961594727"^^xsd:float ;
    mtr:z_score "-10.449638364185274"^^xsd:float .

mtr:Assoc_rs28415528_GCST90199700_GCST90199731 a ns1:association ;
    ns1:has_object mtr:GCST90199700_GCST90199731 ;
    ns1:has_subject dbsnp:rs28415528 ;
    mtr:beta "-0.1198937"^^xsd:float ;
    mtr:denominator_driven false ;
    mtr:effect_allele "A" ;
    mtr:maf "0.317654"^^xsd:float ;
    mtr:numerator_driven true ;
    mtr:pgain "1254167773023.4143"^^xsd:float ;
    mtr:reference_allele "G" ;
    mtr:se "0.0121513360670088"^^xsd:float ;
    mtr:z_score "-9.866709252286569"^^xsd:float .

<https://metabolite-ratio-app.unil.ch/rqtl/Assoc_rs35630725;rs1890452_GCST90200274_GCST90200088> a ns1:association ;
    ns1:has_object mtr:GCST90200274_GCST90200088 ;
    ns1:has_subject <http://identifiers.org/dbsnp/rs35630725;rs1890452> ;
    mtr:beta "-0.2354152"^^xsd:float ;
    mtr:denominator_driven true ;
    mtr:effect_allele "A" ;
    mtr:maf "0.337664"^^xsd:float ;
    mtr:numerator_driven false ;
    mtr:pgain "72488463.52719653"^^xsd:float ;
    mtr:reference_allele "G" ;
    mtr:se "0.0201767725828933"^^xsd:float ;
    mtr:z_score "-11.66763410911386"^^xsd:float .

mtr:Assoc_rs4683709_GCST90200062_GCST90199794 a ns1:association ;
    ns1:has_object mtr:GCST90200062_GCST90199794 ;
    ns1:has_subject dbsnp:rs4683709 ;
    mtr:beta "-0.1664582"^^xsd:float ;
    mtr:denominator_driven false ;
    mtr:effect_allele "T" ;
    mtr:maf "0.336005"^^xsd:float ;
    mtr:numerator_driven false ;
    mtr:pgain "36355577.172539495"^^xsd:float ;
    mtr:reference_allele "G" ;
    mtr:se "0.0206265303537065"^^xsd:float ;
    mtr:z_score "-8.07010181283776"^^xsd:float .

mtr:Assoc_rs4881413_GCST90199851_GCST90199752 a ns1:association ;
    ns1:has_object mtr:GCST90199851_GCST90199752 ;
    ns1:has_subject dbsnp:rs4881413 ;
    mtr:beta "-0.2136051"^^xsd:float ;
    mtr:denominator_driven false ;
    mtr:effect_allele "T" ;
    mtr:maf "0.149779"^^xsd:float ;
    mtr:numerator_driven true ;
    mtr:pgain "23311882719429.81"^^xsd:float ;
    mtr:reference_allele "G" ;
    mtr:se "0.0209935049453722"^^xsd:float ;
    mtr:z_score "-10.17481838101008"^^xsd:float .

mtr:Assoc_rs7160525_GCST90200035_GCST90200125 a ns1:association ;
    ns1:has_object mtr:GCST90200035_GCST90200125 ;
    ns1:has_subject dbsnp:rs7160525 ;
    mtr:beta "-0.399479"^^xsd:float ;
    mtr:denominator_driven true ;
    mtr:effect_allele "A" ;
    mtr:maf "0.164112"^^xsd:float ;
    mtr:numerator_driven true ;
    mtr:pgain "9.516478778920801e+39"^^xsd:float ;
    mtr:reference_allele "G" ;
    mtr:se "0.0221292240491354"^^xsd:float ;
    mtr:z_score "-18.05210156094951"^^xsd:float .

mtr:Assoc_rs74827952_GCST90199851_GCST90199752 a ns1:association ;
    ns1:has_object mtr:GCST90199851_GCST90199752 ;
    ns1:has_subject dbsnp:rs74827952 ;
    mtr:beta "-0.2170323"^^xsd:float ;
    mtr:denominator_driven false ;
    mtr:effect_allele "A" ;
    mtr:maf "0.14828"^^xsd:float ;
    mtr:numerator_driven true ;
    mtr:pgain "20455271808206.95"^^xsd:float ;
    mtr:reference_allele "G" ;
    mtr:se "0.0210562170258713"^^xsd:float ;
    mtr:z_score "-10.30727883044408"^^xsd:float .

mtr:Causal_GTEx_ACADM_to_ratio_GCST90200274_GCST90200088 a mtr:CausalAssessment ;
    mtr:alpha "-0.2823937531698927"^^xsd:float,
        "-0.1271233793707109"^^xsd:float,
        "-0.1269224847399764"^^xsd:float,
        "-0.1106813724812365"^^xsd:float,
        "-0.0908580819366482"^^xsd:float,
        "-0.0716190988382934"^^xsd:float,
        "-0.0461782574039764"^^xsd:float,
        "0.0521291778119246"^^xsd:float,
        "0.1512333543373564"^^xsd:float ;
    mtr:beta_ivw "-0.37721311784841"^^xsd:float,
        "-0.254123583393757"^^xsd:float,
        "-0.252377777472224"^^xsd:float,
        "-0.248787870787629"^^xsd:float,
        "-0.206386998712746"^^xsd:float,
        "-0.187777865734387"^^xsd:float,
        "-0.147611712183608"^^xsd:float,
        "0.166458179508409"^^xsd:float,
        "0.190664404413241"^^xsd:float ;
    mtr:beta_pca "-0.254995846333023"^^xsd:float,
        "-0.208765416802069"^^xsd:float,
        "-0.207977131902603"^^xsd:float,
        "-0.204098268222813"^^xsd:float,
        "-0.194212768034741"^^xsd:float,
        "-0.15886869446232"^^xsd:float,
        "-0.156925878121567"^^xsd:float,
        "0.167042688692721"^^xsd:float,
        "0.203058838002177"^^xsd:float ;
    mtr:coloc_h3 "0.0040781797875837"^^xsd:float,
        "0.0048313095138366"^^xsd:float,
        "0.0416941805700481"^^xsd:float,
        "0.156758003574853"^^xsd:float,
        "0.175317092133096"^^xsd:float,
        "0.180658304744757"^^xsd:float,
        "0.194645587457445"^^xsd:float,
        "0.845851405209382"^^xsd:float,
        "0.991832393880724"^^xsd:float ;
    mtr:coloc_h4 "0.007403442238362"^^xsd:float,
        "0.154148591832652"^^xsd:float,
        "0.805354412542553"^^xsd:float,
        "0.819341695255246"^^xsd:float,
        "0.824682907866904"^^xsd:float,
        "0.843133745116764"^^xsd:float,
        "0.958305819428457"^^xsd:float,
        "0.995168689954794"^^xsd:float,
        "0.99592182021239"^^xsd:float ;
    mtr:dataset_source "GTEx" ;
    mtr:has_exposure <http://identifiers.org/hgnc.symbol/ACADM> ;
    mtr:has_outcome mtr:GCST90200274_GCST90200088 ;
    mtr:measured_in_tissue "Adipose_Visceral_Omentum",
        "Adrenal_Gland",
        "Brain_Cerebellar_Hemisphere",
        "Brain_Cerebellum",
        "Colon_Sigmoid",
        "Esophagus_Muscularis",
        "Heart_Atrial_Appendage",
        "Skin_Not_Sun_Exposed_Suprapubic",
        "Whole_Blood" ;
    mtr:p_ivw "3.0596235480788995e-31"^^xsd:float,
        "4.93311286914619e-31"^^xsd:float,
        "1.78867048294016e-29"^^xsd:float,
        "3.8019801965460494e-25"^^xsd:float,
        "3.4233711425358104e-20"^^xsd:float,
        "5.87508206058703e-20"^^xsd:float,
        "1.53917749411634e-07"^^xsd:float,
        "0.308587221710117"^^xsd:float ;
    mtr:p_pca "1.5187883997519998e-35"^^xsd:float,
        "1.10185234572734e-30"^^xsd:float,
        "4.89538351625016e-30"^^xsd:float,
        "7.70411081813631e-19"^^xsd:float,
        "1.45722422534276e-18"^^xsd:float,
        "1.01238495434857e-17"^^xsd:float,
        "2.15311412432745e-17"^^xsd:float,
        "2.4388917205669904e-15"^^xsd:float,
        "1.93552047650081e-10"^^xsd:float ;
    mtr:se_ivw "0.0164005985498081"^^xsd:float,
        "0.0181989030705326"^^xsd:float,
        "0.0183084658784187"^^xsd:float,
        "0.0217856427750844"^^xsd:float,
        "0.0225431494449013"^^xsd:float,
        "0.0240161686205748"^^xsd:float,
        "0.0281282490461484"^^xsd:float,
        "0.0409800855031656"^^xsd:float,
        "0.184423036376777"^^xsd:float ;
    mtr:snps_overlap 320,
        322,
        337 ;
    mtr:susie_h4 "0.0005737261794821"^^xsd:float,
        "0.0290749637305896"^^xsd:float,
        "0.0873206606119574"^^xsd:float,
        "0.0885773210707393"^^xsd:float,
        "0.0894231263904837"^^xsd:float,
        "0.96695881804385"^^xsd:float,
        "0.971673376814113"^^xsd:float,
        "0.995857498042386"^^xsd:float,
        "0.998269934015322"^^xsd:float ;
    mtr:target_level "ratio" ;
    mtr:variance_explained "0.99"^^xsd:float .

mtr:Causal_GTEx_ACSL6_to_ratio_GCST90199713_GCST90199730 a mtr:CausalAssessment ;
    mtr:alpha "-0.286587540332527"^^xsd:float,
        "-0.2514338233753426"^^xsd:float ;
    mtr:beta_pca "-0.258823522169908"^^xsd:float,
        "-0.16418019945224"^^xsd:float ;
    mtr:coloc_h3 "0.0132322325434715"^^xsd:float,
        "0.0269747208308598"^^xsd:float ;
    mtr:coloc_h4 "0.82857850523674"^^xsd:float,
        "0.931484429818369"^^xsd:float ;
    mtr:dataset_source "GTEx" ;
    mtr:has_exposure <http://identifiers.org/hgnc.symbol/ACSL6> ;
    mtr:has_outcome mtr:GCST90199713_GCST90199730 ;
    mtr:measured_in_tissue "Esophagus_Gastroesophageal_Junction",
        "Pituitary" ;
    mtr:p_pca "2.33011991248657e-17"^^xsd:float,
        "1.01488261444098e-06"^^xsd:float ;
    mtr:snps_overlap 321,
        327 ;
    mtr:target_level "ratio" ;
    mtr:variance_explained "0.99"^^xsd:float .

mtr:Causal_GTEx_BEST1_to_ratio_GCST90199710_GCST90200086 a mtr:CausalAssessment ;
    mtr:alpha "0.665949792952153"^^xsd:float ;
    mtr:beta_pca "0.222939587294317"^^xsd:float ;
    mtr:coloc_h3 "0.0304832166097938"^^xsd:float ;
    mtr:coloc_h4 "0.85659355946338"^^xsd:float ;
    mtr:dataset_source "GTEx" ;
    mtr:has_exposure <http://identifiers.org/hgnc.symbol/BEST1> ;
    mtr:has_outcome mtr:GCST90199710_GCST90200086 ;
    mtr:measured_in_tissue "Esophagus_Muscularis" ;
    mtr:p_pca "9.75646679590554e-12"^^xsd:float ;
    mtr:snps_overlap 594 ;
    mtr:target_level "ratio" ;
    mtr:variance_explained "0.99"^^xsd:float .

mtr:Causal_GTEx_BEST1_to_ratio_GCST90200330_GCST90199899 a mtr:CausalAssessment ;
    mtr:alpha "0.8336136965492547"^^xsd:float ;
    mtr:beta_pca "0.292975586954029"^^xsd:float ;
    mtr:coloc_h3 "0.0057014916892325"^^xsd:float ;
    mtr:coloc_h4 "0.97027226999216"^^xsd:float ;
    mtr:dataset_source "GTEx" ;
    mtr:has_exposure <http://identifiers.org/hgnc.symbol/BEST1> ;
    mtr:has_outcome mtr:GCST90200330_GCST90199899 ;
    mtr:measured_in_tissue "Esophagus_Muscularis" ;
    mtr:p_pca "9.94641789048519e-24"^^xsd:float ;
    mtr:snps_overlap 597 ;
    mtr:target_level "ratio" ;
    mtr:variance_explained "0.99"^^xsd:float .

mtr:Causal_GTEx_CYP4A11_to_ratio_GCST90200529_GCST90200530 a mtr:CausalAssessment ;
    mtr:alpha "-0.3143873739797006"^^xsd:float,
        "-0.2891070092529136"^^xsd:float,
        "-0.232187228790668"^^xsd:float,
        "-0.1464785115022483"^^xsd:float ;
    mtr:beta_ivw "-0.233917642875839"^^xsd:float,
        "-0.228031814429345"^^xsd:float ;
    mtr:beta_pca "-0.25930557069485"^^xsd:float,
        "-0.238606267912574"^^xsd:float,
        "-0.238428235719057"^^xsd:float,
        "-0.197404176815392"^^xsd:float ;
    mtr:coloc_h3 "0.0288863989041834"^^xsd:float,
        "0.0724568343834121"^^xsd:float,
        "0.157983005213132"^^xsd:float,
        "0.160468276445132"^^xsd:float ;
    mtr:coloc_h4 "0.839064222515056"^^xsd:float,
        "0.839190003518805"^^xsd:float,
        "0.92753346321785"^^xsd:float,
        "0.958774166179588"^^xsd:float ;
    mtr:dataset_source "GTEx" ;
    mtr:has_exposure <http://identifiers.org/hgnc.symbol/CYP4A11> ;
    mtr:has_outcome mtr:GCST90200529_GCST90200530 ;
    mtr:measured_in_tissue "Adipose_Visceral_Omentum",
        "Breast_Mammary_Tissue",
        "Lung",
        "Testis" ;
    mtr:p_ivw "6.83460835906337e-10"^^xsd:float ;
    mtr:p_pca "1.64230602679997e-11"^^xsd:float,
        "2.22704908033629e-10"^^xsd:float,
        "3.04560224071078e-10"^^xsd:float,
        "1.0574423452478e-07"^^xsd:float ;
    mtr:se_ivw "0.0369589323106121"^^xsd:float,
        "0.0379128954042719"^^xsd:float ;
    mtr:snps_overlap 326,
        331 ;
    mtr:susie_h4 "0.249263532657997"^^xsd:float,
        "0.568630609521515"^^xsd:float,
        "0.813718686067121"^^xsd:float,
        "0.918066507822797"^^xsd:float ;
    mtr:target_level "ratio" ;
    mtr:variance_explained "0.99"^^xsd:float .

mtr:Causal_GTEx_CYP4A22_to_ratio_GCST90200529_GCST90200530 a mtr:CausalAssessment ;
    mtr:alpha "0.0689863796577135"^^xsd:float,
        "0.2213285642282169"^^xsd:float,
        "0.267673303129938"^^xsd:float ;
    mtr:beta_ivw "0.167870033077107"^^xsd:float ;
    mtr:beta_pca "0.0935688487007326"^^xsd:float,
        "0.172077515013396"^^xsd:float,
        "0.187062411304749"^^xsd:float ;
    mtr:coloc_h3 "0.0298887832793481"^^xsd:float,
        "0.0411532559136271"^^xsd:float,
        "0.157350920265362"^^xsd:float ;
    mtr:coloc_h4 "0.826557026402522"^^xsd:float,
        "0.875619168528709"^^xsd:float,
        "0.888752857622624"^^xsd:float ;
    mtr:dataset_source "GTEx" ;
    mtr:has_exposure <http://identifiers.org/hgnc.symbol/CYP4A22> ;
    mtr:has_outcome mtr:GCST90200529_GCST90200530 ;
    mtr:measured_in_tissue "Brain_Hippocampus",
        "Brain_Hypothalamus",
        "Small_Intestine_Terminal_Ileum" ;
    mtr:p_ivw "6.83460835906337e-10"^^xsd:float ;
    mtr:p_pca "6.56515422051837e-10"^^xsd:float,
        "7.75263110480752e-09"^^xsd:float,
        "3.54057489960486e-06"^^xsd:float ;
    mtr:se_ivw "0.0272080332518663"^^xsd:float ;
    mtr:snps_overlap 251,
        292,
        331 ;
    mtr:susie_h4 "0.271270251808195"^^xsd:float ;
    mtr:target_level "ratio" ;
    mtr:variance_explained "0.99"^^xsd:float .

mtr:Causal_GTEx_CYP4Z1_to_ratio_GCST90200529_GCST90200530 a mtr:CausalAssessment ;
    mtr:alpha "-0.1065176501523218"^^xsd:float ;
    mtr:beta_ivw "-0.0288625588251722"^^xsd:float ;
    mtr:beta_pca "-0.0861568574031135"^^xsd:float ;
    mtr:coloc_h3 "0.675734326745647"^^xsd:float ;
    mtr:coloc_h4 "0.317851372483691"^^xsd:float ;
    mtr:dataset_source "GTEx" ;
    mtr:has_exposure <http://identifiers.org/hgnc.symbol/CYP4Z1> ;
    mtr:has_outcome mtr:GCST90200529_GCST90200530 ;
    mtr:measured_in_tissue "Thyroid" ;
    mtr:p_ivw "0.553323491466865"^^xsd:float ;
    mtr:p_pca "0.0061012488942103"^^xsd:float ;
    mtr:se_ivw "0.0486895681041338"^^xsd:float ;
    mtr:snps_overlap 331 ;
    mtr:susie_h4 "0.947666269308566"^^xsd:float ;
    mtr:target_level "ratio" ;
    mtr:variance_explained "0.99"^^xsd:float .

mtr:Causal_GTEx_FADS1_to_ratio_GCST90199710_GCST90200086 a mtr:CausalAssessment ;
    mtr:alpha "-1.1582362784780087"^^xsd:float,
        "-0.9698495633919706"^^xsd:float,
        "-0.9434374763590734"^^xsd:float,
        "-0.92113641692632"^^xsd:float,
        "-0.8455652298304337"^^xsd:float,
        "-0.7546971992583509"^^xsd:float,
        "-0.6500765161460882"^^xsd:float,
        "-0.64533769974136"^^xsd:float,
        "-0.6449521300493435"^^xsd:float,
        "-0.6337553783376988"^^xsd:float,
        "-0.6179630755963956"^^xsd:float,
        "-0.6102838448881174"^^xsd:float,
        "-0.5520812049679342"^^xsd:float,
        "-0.5347640018119806"^^xsd:float,
        "-0.5294015723256081"^^xsd:float,
        "-0.5231526051809401"^^xsd:float,
        "-0.4915775944783639"^^xsd:float,
        "-0.4886232134069044"^^xsd:float,
        "-0.4860648038041826"^^xsd:float,
        "-0.4749193853006876"^^xsd:float,
        "-0.451961856278575"^^xsd:float,
        "-0.4031595073835142"^^xsd:float,
        "-0.3881605582664174"^^xsd:float,
        "-0.3721930891691499"^^xsd:float,
        "-0.3598555794091944"^^xsd:float,
        "-0.3362432032718815"^^xsd:float,
        "-0.31624029426964"^^xsd:float,
        "-0.3111209916118619"^^xsd:float,
        "-0.2889547561759448"^^xsd:float,
        "-0.2835881200806991"^^xsd:float,
        "-0.1317192051351054"^^xsd:float ;
    mtr:beta_ivw "-0.779563251446557"^^xsd:float,
        "-0.750029415305739"^^xsd:float,
        "-0.595998608104477"^^xsd:float,
        "-0.594900981781828"^^xsd:float,
        "-0.545558944034201"^^xsd:float,
        "-0.51523261783516"^^xsd:float,
        "-0.471475258880139"^^xsd:float,

<font size="4"> "What are the most statistically significant genetic associations in the GWAS Catalog currently stored in our graph, and what are their specific effect sizes, risk alleles, and original publication IDs?"
</font>

In [38]:
df_results = query_graphdb("../analysis/002_query.rq", repo_name="mtrKG")

# Display the results
df_results

Reading SPARQL query from file: ../analysis/002_query.rq
Sending query to GraphDB (mtrKG)...
Success! Retrieved 118 rows.

,snp_id,strongest_gwas_p_value,associated_clinical_traits,driven_metabolic_ratios
0,rs102275,4e-264,coronary artery calcification | lysophosphatid...,"1,2-dilinoleoyl-gpc (18:2/18:2) to 1-lignocero..."
1,rs1047891,0.0,glycine measurement | gamma-glutamylglycine me...,choline to isovalerylglycine | n-palmitoylglyc...
2,rs1260326,0.0,triglyceride measurement | triglycerides in me...,"sphingomyelin (d17:1/16:0, d18:1/15:0, d16:1/1..."
3,rs174560,4e-59,1-stearoyl-2-arachidonoyl-GPI (18:0/20:4) meas...,dihomo-linolenate (20:3n3 or n6) to arachidono...
4,rs4814176,3e-107,level of ceramide | sphingomyelin measurement ...,lignoceroyl sphingomyelin (d18:1/24:0) to sphi...
...,...,...,...,...
113,rs1767447,2e-11,heel bone mineral density,phosphoethanolamine to 1-stearoyl-2-oleoyl-gps...
114,rs12095130,3e-10,X-21607 measurement,x-16397 to x-17335
115,rs7573275,2e-09,self reported educational attainment | N-delta...,"n2-acetyl,n6,n6-dimethyllysine to x-12112 | 2-..."
116,rs34048349,2e-09,body height,"5alpha-androstan-3beta,17beta-diol monosulfate..."
117,rs10212439,3.0000000000000004e-08,level of phosphatidylinositol,1-linoleoyl-gpe (18:2)* to 1-oleoyl-gpe (18:1)

<font size="4"> Find me a severe clinical disease from the GWAS Catalog that is driven by a specific genetic variant. Then, show me the metabolic ratio disrupted by that variant, the causal enzyme responsible for the disruption, and finally, check if there is an FDA-approved drug (Phase 3 or 4) that already targets that enzyme."
</font>

In [40]:
df_results = query_graphdb("../analysis/003_query.rq", repo_name="mtrKG")

# Display the results
display(df_results)

Reading SPARQL query from file: ../analysis/003_query.rq
Sending query to GraphDB (mtrKG)...
Success! Retrieved 20 rows.

,disease_name,ratio_name,causal_gene,drug_name,max_phase
0,16a-hydroxy DHEA 3-sulfate measurement,"androstenediol (3beta,17beta) disulfate (2) to...",CYP3A5,RITONAVIR,4
1,16a-hydroxy DHEA 3-sulfate measurement,"5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A5,RITONAVIR,4
2,16a-hydroxy DHEA 3-sulfate measurement,"androstenediol (3beta,17beta) disulfate (2) to...",CYP3A7,RITONAVIR,4
3,16a-hydroxy DHEA 3-sulfate measurement,"5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A7,RITONAVIR,4
4,16a-hydroxy DHEA 3-sulfate measurement,"androstenediol (3beta,17beta) disulfate (2) to...",CYP3A5,COBICISTAT,4
5,16a-hydroxy DHEA 3-sulfate measurement,"5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A5,COBICISTAT,4
6,16a-hydroxy DHEA 3-sulfate measurement,"androstenediol (3beta,17beta) disulfate (2) to...",CYP3A7,COBICISTAT,4
7,16a-hydroxy DHEA 3-sulfate measurement,"5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A7,COBICISTAT,4
8,"5alpha-androstan-3alpha,17beta-diol monosulfat...","androstenediol (3beta,17beta) disulfate (2) to...",CYP3A5,RITONAVIR,4
9,"5alpha-androstan-3alpha,17beta-diol monosulfat...","5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A5,RITONAVIR,4
10,"5alpha-androstan-3alpha,17beta-diol monosulfat...","androstenediol (3beta,17beta) disulfate (2) to...",CYP3A7,RITONAVIR,4
11,"5alpha-androstan-3alpha,17beta-diol monosulfat...","5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A7,RITONAVIR,4
12,"5alpha-androstan-3alpha,17beta-diol monosulfat...","androstenediol (3beta,17beta) disulfate (2) to...",CYP3A5,COBICISTAT,4
13,"5alpha-androstan-3alpha,17beta-diol monosulfat...","5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A5,COBICISTAT,4
14,"5alpha-androstan-3alpha,17beta-diol monosulfat...","androstenediol (3beta,17beta) disulfate (2) to...",CYP3A7,COBICISTAT,4
15,"5alpha-androstan-3alpha,17beta-diol monosulfat...","5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A7,COBICISTAT,4
16,Free cholesterol:total lipids ratio,"sphingomyelin (d18:1/20:2, d18:2/20:1, d16:1/2...",SLC22A6,PROBENECID,4
17,N-acetylglycine measurement,n-palmitoylglycine to eicosenoate (20:1),FAAH,ACETAMINOPHEN,4
18,N-acetylglycine measurement,2-butenoylglycine to x-12101,NDUFV1,METFORMIN,4
19,N-acetylglycine measurement,2-butenoylglycine to x-12101,NDUFV1,METFORMIN HYDROCHLORIDE,4

<font size="4"> We found a gene that causally drives a metabolic imbalance linked to a disease. However, what if that specific gene is considered 'undruggable' (no known drugs)? Can the Knowledge Graph find an FDA-approved drug that targets a different protein, as long as that protein physically binds to our undruggable causal gene?"
</font>

In [41]:
df_results = query_graphdb("../analysis/004_query.rq", repo_name="mtrKG")

# Display the results
display(df_results)

Reading SPARQL query from file: ../analysis/004_query.rq
Sending query to GraphDB (mtrKG)...
Success! Retrieved 20 rows.

,ratio_name,causal_gene_name,interacting_gene_name,interaction_score,drug_name,clinical_phase
0,"androstenediol (3beta,17beta) disulfate (2) to...",CYP3A5,CYP3A7,0.968,RITONAVIR,4
1,"5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A5,CYP3A7,0.968,RITONAVIR,4
2,"androstenediol (3beta,17beta) disulfate (2) to...",CYP3A5,CYP3A7,0.968,COBICISTAT,4
3,"5alpha-androstan-3beta,17beta-diol monosulfate...",CYP3A5,CYP3A7,0.968,COBICISTAT,4
4,3-hydroxysebacate to 2-butenoylglycine,CYP4A11,CYP3A7,0.948,RITONAVIR,4
5,3-hydroxysebacate to x-14939,CYP4A11,CYP3A7,0.948,RITONAVIR,4
6,2-hydroxysebacate to x-18913,CYP4A11,CYP3A7,0.948,RITONAVIR,4
7,x-16580 to x-12839,CYP4A11,CYP3A7,0.948,RITONAVIR,4
8,x-16397 to x-17335,CYP4A11,CYP3A7,0.948,RITONAVIR,4
9,pregnenolone sulfate to 21-hydroxypregnenolone...,CYP4A11,CYP3A7,0.948,RITONAVIR,4
10,adipoylcarnitine (c6-dc) to x-24949,CYP4A11,CYP3A7,0.948,RITONAVIR,4
11,dodecenedioate (c12:1-dc)* to glycine conjugat...,CYP4A11,CYP3A7,0.948,RITONAVIR,4
12,3-hydroxysebacate to 2-butenoylglycine,CYP4A11,CYP3A7,0.948,COBICISTAT,4
13,3-hydroxysebacate to x-14939,CYP4A11,CYP3A7,0.948,COBICISTAT,4
14,2-hydroxysebacate to x-18913,CYP4A11,CYP3A7,0.948,COBICISTAT,4
15,x-16580 to x-12839,CYP4A11,CYP3A7,0.948,COBICISTAT,4
16,x-16397 to x-17335,CYP4A11,CYP3A7,0.948,COBICISTAT,4
17,pregnenolone sulfate to 21-hydroxypregnenolone...,CYP4A11,CYP3A7,0.948,COBICISTAT,4
18,adipoylcarnitine (c6-dc) to x-24949,CYP4A11,CYP3A7,0.948,COBICISTAT,4
19,dodecenedioate (c12:1-dc)* to glycine conjugat...,CYP4A11,CYP3A7,0.948,COBICISTAT,4

<font size="4"> ENCODE for epigenetics "
</font>

In [56]:
df_results = query_graphdb("../analysis/005_query.rq", repo_name="mtrKG")

# Display the results
display(df_results)

Reading SPARQL query from file: ../analysis/005_query.rq
Sending query to GraphDB (mtrKG)...
Success! Retrieved 7 rows.

       snp_id        regulatory_element
0    rs174560   enhancer (ENSR11_C85LJ)
1    rs174564   enhancer (ENSR11_9WJJ2)
2   rs1767447    enhancer (ENSR1_C45RM)
3   rs2062541   enhancer (ENSR16_98CSB)
4  rs61797339   promoter (ENSR1_9353HX)
5  rs73355734  enhancer (ENSR17_935633)
6    rs924135   enhancer (ENSR16_98CR7)

In [30]:
execute_sparql(g,optimized_gwas_query)

Executing SPARQL query...

KeyboardInterrupt:

In [37]:
execute_sparql(g,optimized_gwas_query)

Executing SPARQL query...

KeyboardInterrupt:

In [47]:
g.serialize(destination="../output/mtrKG.ttl", format="turtle")

In [ ]:
g = enrich_graph_with_reactome(g)

# 5. NetworkX Graph Analytics
print("\n[STEP 3] Running Graph Analytics...")
g = calculate_reaction_distances(g)

# 6. SHACL Validation
print("\n[STEP 4] Validating Graph structure...")
validate_graph_with_shacl(g)

# 7. Save Output
output_path = "output/final_knowledge_graph.ttl"
g.serialize(destination=output_path, format="turtle")
print(f"\n[SUCCESS] Knowledge Graph saved to {output_path} with {len(g)} triples!")